services:
  postgres:
    image: postgres:15
    container_name: amd_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python-service:
    build: ./python-service    # âœ… build from folder
    container_name: amd_python
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - postgres

volumes:
  postgres_data:
